apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test-argo
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.access.redhat.com/ubi8/nginx-120@sha256:4179da7a92814535a2ea0390802a4306906ccd888045819eb9f6e17f2ac35dda
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "1"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
