apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
  name: hpa-hello
  namespace: test-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: hello-1
      target:
        type: Utilization
        averageUtilization: 50
  - type: ContainerResource
    containerResource:
      name: cpu
      container: hello-2
      target:
        type: Utilization
        averageUtilization: 50
