apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
    db: mysql
  name: mysql
  namespace: test-argo
spec:
  ports:
  - name: 3306-tcp
    port: 3306
  selector:
    db: mysql
    deployment: mysql
