apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-mysq
    db: deploy-mysq
  name: deploy-mysq
  namespace: test-argo
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      db: deploy-mysq
      deployment: deploy-mysq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        db: deploy-mysq
        deployment: deploy-mysq
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: testdb
        - name: MYSQL_PASSWORD
          value: pass
        - name: MYSQL_USER
          value: user
        - name: MYSQL_ROOT_PASSWORD
          value: test
        - name: DUMMY
          value: test
        image: docker.io/mysql:latest
        imagePullPolicy: IfNotPresent
        name: deploy-mysq
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: 500m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
